// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AntDesign:fileMarkdownOutlined': typeof import('~icons/ant-design/file-markdown-outlined')['default']
    'Bx:bxCheckbox': typeof import('~icons/bx/bx-checkbox')['default']
    'Bx:bxCheckboxChecked': typeof import('~icons/bx/bx-checkbox-checked')['default']
    'Bx:bxCheckboxMinus': typeof import('~icons/bx/bx-checkbox-minus')['default']
    'Bx:bxSearchAlt': typeof import('~icons/bx/bx-search-alt')['default']
    'Carbon:document': typeof import('~icons/carbon/document')['default']
    'Carbon:listDropdown': typeof import('~icons/carbon/list-dropdown')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CurrentIndex: typeof import('./components/CurrentIndex.vue')['default']
    'Fluent:databaseSearch24Regular': typeof import('~icons/fluent/database-search24-regular')['default']
    FooBar: typeof import('./components/FooBar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Iconoir:download': typeof import('~icons/iconoir/download')['default']
    LinkValidation: typeof import('./components/LinkValidation.vue')['default']
    'Mdi:folderHome': typeof import('~icons/mdi/folder-home')['default']
    'Mdi:github': typeof import('~icons/mdi/github')['default']
    'Mdi:languageRust': typeof import('~icons/mdi/language-rust')['default']
    'Mdi:languageTypescript': typeof import('~icons/mdi/language-typescript')['default']
    MissingIndex: typeof import('./components/MissingIndex.vue')['default']
    'Octicon:trash16': typeof import('~icons/octicon/trash16')['default']
    'Ph:info': typeof import('~icons/ph/info')['default']
    'Ph:linkLight': typeof import('~icons/ph/link-light')['default']
    README: typeof import('./components/README.md')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SearchHit: typeof import('./components/SearchHit.vue')['default']
    SearchIndexes: typeof import('./components/SearchIndexes.vue')['default']
    SearchResults: typeof import('./components/SearchResults.vue')['default']
    'Tabler:databaseImport': typeof import('~icons/tabler/database-import')['default']
    'Teenyicons:dockerOutline': typeof import('~icons/teenyicons/docker-outline')['default']
    'Teenyicons:textDocumentSolid': typeof import('~icons/teenyicons/text-document-solid')['default']
    'VscodeIcons:fileTypeRust': typeof import('~icons/vscode-icons/file-type-rust')['default']
    'VscodeIcons:fileTypeTypescriptOfficial': typeof import('~icons/vscode-icons/file-type-typescript-official')['default']
  }
}

export { }
