// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CurrentIndex: typeof import('./components/CurrentIndex.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MissingIndex: typeof import('./components/MissingIndex.vue')['default']
    README: typeof import('./components/README.md')['default']
    SearchHit: typeof import('./components/SearchHit.vue')['default']
    SearchIndexes: typeof import('./components/SearchIndexes.vue')['default']
    SearchResults: typeof import('./components/SearchResults.vue')['default']
    SimpleCard: typeof import('./components/SimpleCard.vue')['default']
  }
}

export { }
