// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Bx:bxSearchAlt': typeof import('~icons/bx/bx-search-alt')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    'Fluent:databaseSearch24Regular': typeof import('~icons/fluent/database-search24-regular')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    'Ic:roundScreenSearchDesktop': typeof import('~icons/ic/round-screen-search-desktop')['default']
    'Mdi:folderHome': typeof import('~icons/mdi/folder-home')['default']
    'Mdi:languageRust': typeof import('~icons/mdi/language-rust')['default']
    'Mdi:languageTypescript': typeof import('~icons/mdi/language-typescript')['default']
    README: typeof import('./components/README.md')['default']
    SimpleCard: typeof import('./components/SimpleCard.vue')['default']
    'Tabler:databaseImport': typeof import('~icons/tabler/database-import')['default']
    'Teenyicons:dockerOutline': typeof import('~icons/teenyicons/docker-outline')['default']
  }
}

export { }
