# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: 'Prepare Environment'
description: 'installs pnpm, installs all deps in each package'

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - name: Setup Node
    uses: actions/setup-node@v2
    with:
      node-version: 16
      cache: 'npm'
      cache-dependency-path: 'pnpm-lock.yml'
  - name: Install PNPM and Dependencies
    shell: bash
    run: |
      npm i -g pnpm
      pnpm install --ignore-scripts
      cd packages/tauri-search
      pnpm install --ignore-scripts
      cd ../docs
      pnpm install --ignore-scripts
      cd ..
  - name: Build CLI and NPM exports
    shell: bash
    run: pnpm run build
  - name: Environment Prepped
    shell: bash
    run: echo Node, pnpm, and all deps are installed!